version: "3.8"
volumes:
  postgres_data: {}

services:
  backend:
    container_name: denti-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3200:3000"
    environment:
      RAILS_ENV: 'development'
      DB_HOST: db
      DB_NAME: patient_db
      DB_USERNAME: postgres
      DB_PASSWORD: Sistemas2023*
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
    volumes:
      - .:/usr/src/d-app
    command: rails s -b 0.0.0.0
    depends_on:
      - db

  db:
    container_name: d-pgdb
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sistemas2023*